CREATE DATABASE [SoftUni]

CREATE TABLE [Towns] (
	[Id] INT PRIMARY KEY IDENTITY NOT NULL,
	[Name] NVARCHAR(70) NOT NULL
)

CREATE TABLE [Addresses] (
	[Id] INT PRIMARY KEY IDENTITY NOT NULL,
	[AddressText] NVARCHAR(50) NOT NULL,
	[TownId] INT UNIQUE FOREIGN KEY ([TownId]) REFERENCES [Towns](Id)
)

CREATE TABLE [Departments] (
	[Id] INT PRIMARY KEY IDENTITY NOT NULL,
	[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE [Employees] (
	[Id] INT PRIMARY KEY IDENTITY NOT NULL,
	[FirstName] NVARCHAR(60) NOT NULL,
	[MiddleName] NVARCHAR(60) NOT NULL,
	[LastName] NVARCHAR(60) NOT NULL,
	[JobTitle] NVARCHAR(30),
	[DepartmentId] INT UNIQUE FOREIGN KEY ([DepartmentId]) REFERENCES [Departments]([Id]),
	[HireDate] DATE NOT NULL,
	[Salary] DECIMAL NOT NULL,
	[AddressId] INT UNIQUE FOREIGN KEY ([AddressId]) REFERENCES [Addresses]([Id])
)