CREATE TABLE [Passports] (
	[PassportID] INT PRIMARY KEY IDENTITY(101, 1) NOT NULL,
	[PassportNumber] VARCHAR(40) NOT NULL
)

CREATE TABLE [Persons] (
	[PersonID] INT PRIMARY KEY IDENTITY(1, 1),
	[FirstName] NVARCHAR(40) NOT NULL,
	[Salary] DECIMAL NOT NULL,
	[PassportID] INT
	CONSTRAINT FK_PassportID FOREIGN KEY ([PassportID])
	REFERENCES [Passports]([PassportID])
)

INSERT INTO [Passports] VALUES
('N34FG21B'),
('K65LO4R7'),
('ZE657QP2')

INSERT INTO [Persons] VALUES
('Roberto', 43300.00, 102),
('Tom', 56100.00, 103),
('Yana', 60200.00, 101)

